### ISSUE TITLE
quest book and recipe issues lve found so far

### ISSUE THREAD

**Issue by MASONHAA** [Zak223/Nepturon-skyblock#11]
with the basic items string mesh quest you cant get redstone from string mesh
the lv solar panel quest is impossible at this stage due to the fact that it requires luv circuits
in order to get the induction smelter you need invar which need nickel which is impossible to get without a iron stiffened mesh which needs steel

**Comment by MASONHAA** [comment]
another one is that red alloy wire is ulv lossless not lv

**Comment by Zak223** [comment]
- [ ] Add Nickel to Flint Meshes
- [ ] Change LV lossless cables to right type 
- [x] Redstone and Solar panels issue #10
